services:
  service:
    image: localhost/dservice:latest
    container_name: dservice

  monitor:
    image: localhost/monitor:latest
    container_name: monitor
    volumes:
    - ../Monitor/config.yaml:/monitor/config.yaml
    ports:
    - "8081:8081"
    depends_on:
      - service
