services:
  service:
    image: localhost/dservice:1
    container_name: dservice

  monitor:
    image: localhost/monitor:1
    container_name: monitor
    volumes:
    - ../Monitor/config.yaml:/monitor/config.yaml
    ports:
    - "8081:8081"
    depends_on:
      - service