services:
  service:
    image: localhost/dservice:latest
    container_name: dservice

  monitor:
    image: localhost/monitor:latest
    container_name: monitor
    volumes:
    - ../Monitor/config.yaml:/monitor/config.yaml
    ports:
    - "8081:8081"
    depends_on:
      - service

  prometheus:
    image: docker.io/prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - monitor
      - alertmanager

  grafana:
    image: docker.io/grafana/grafana:main
    container_name: grafana
    volumes:
      - /grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  alertmanager:
    image: docker.io/prom/alertmanager
    container_name: alertmanager
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
    - "9093:9093"


volumes:
  prometheus_data: