global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "monitor"
    static_configs:
      - targets: ["monitor:8081"]

rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
